apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app-deployment
  labels:
    app: mon-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mon-app
  template:
    metadata:
      labels:
        app: mon-app
    spec:
      containers:
      - name: mon-app-python
        image: brayanlaw/mon-app-python:latest
        ports:
        - containerPort: 80
        
        # --- SONDES DE SANTÉ (Probes) ---
        # Vérifie si le conteneur est prêt à recevoir du trafic réseau
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

        # Vérifie si l'application fonctionne toujours correctement
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10