name: Pipeline CI/CD Avance (Tests, Qualite, Security & CD)

on:
  push:
    branches: [ "main" ]

jobs:
  # Job 1 : Qualité du code Python & Tests unitaires
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les dependances
        run: |
          python -m pip install --upgrade pip
          pip install -r docker_app/requirements.txt
          pip install pytest flake8

      - name: Linting avec Flake8
        run: |
          # Stop le build si erreur de syntaxe ou variables non définies
          flake8 docker_app --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Execution des tests unitaires avec Pytest
        run: |
          PYTHONPATH=docker_app pytest docker_app

  # Job 2 : Lint du Dockerfile
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Verifier la qualite du Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker_app/Dockerfile

  # Job 3 : Scan des vulnérabilités avec Trivy
  scan-securite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Scanner avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './docker_app'
          severity: 'CRITICAL,HIGH'

  # Job 4 : Build & Push 
  build-and-push:
    needs: [test-python, lint-dockerfile, scan-securite]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Connexion a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build et Push sur Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./docker_app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mon-app-python:latest

# Job 5 : Déploiement sur le serveur
  deploy-staging:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH et mise a jour du conteneur
        run: |
          echo "Simulations du deploiement SSH sur le serveur..."
          echo "1. Connexion SSH au serveur..."
          echo "2. docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mon-app-python:latest"
          echo "3. Redemarrage du service avec le nouveau conteneur"
          echo "Deploiement effectue avec succes !"